### ISSUE TITLE
Anchor link targets are partially occluded by black border

### ISSUE THREAD

**Issue by cbeams** [sapiensoup/sapiensoup.com#20]
![image](https://cloud.githubusercontent.com/assets/301810/21962815/d80bd464-db2e-11e6-9d39-e401206c09b3.png)

See this bit of CSS:

```css
@media screen and (min-width: 44.375em)
body:not(.custom-background-image):before, body:not(.custom-background-image):after {
    background: inherit;
    content: "";
    display: block;
    height: 21px;
    left: 0;
    position: fixed;
    width: 100%;
    z-index: 99;
}
```
